<?php

namespace App\Services;

class FilterRegistry
{
    public static function getFilters(): array
    {
        return [
            // --- Company Filters ---
            [
                'id' => 'company_name',
                'label' => 'Company Name',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'text',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['company'],
                    'contact' => ['company.company'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['company', 'company_also_known_as']],
                'filtering' => ['mode' => 'term', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => false],
                'sort_order' => 10,
                'active' => true,
            ],
            [
                'id' => 'company_domain',
                'label' => 'Company Domain',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'text',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['website'],
                    'contact' => ['company.website'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['website', 'domain']],
                'filtering' => ['mode' => 'term', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => false],
                'sort_order' => 20,
                'active' => true,
            ],
           
            [
                'id' => 'business_category',
                'label' => 'Business Category',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['business_category'],
                    'contact' => ['company.business_category'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['business_category']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 32,
                'active' => true,
            ],
            // [
            //     'id' => 'company_alias',
            //     'label' => 'Also Known As',
            //     'group' => 'Company',
            //     'applies_to' => ['company', 'contact'],
            //     'type' => 'text',
            //     'input' => 'text',
            //     'data_source' => 'elasticsearch',
            //     'fields' => [
            //         'company' => ['company_also_known_as'],
            //         'contact' => ['company.company_also_known_as'],
            //     ],
            //     'search' => ['enabled' => true, 'suggest_fields' => ['company_also_known_as', 'company']],
            //     'filtering' => ['mode' => 'term', 'supports_exclusion' => true],
            //     'aggregation' => ['enabled' => false],
            //     'sort_order' => 25,
            //     'active' => true,
            // ],
            [
                'id' => 'sic_code',
                'label' => 'SIC Code',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['sic_code'],
                    'contact' => ['company.sic_code'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => false],
                'sort_order' => 35,
                'active' => true,
            ],
            [
                'id' => 'keywords',
                'label' => 'Keywords',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'text',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['keywords'],
                    'contact' => ['company.keywords'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'term', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => false],
                'sort_order' => 40,
                'active' => true,
            ],
            [
                'id' => 'technologies',
                'label' => 'Technologies',
                'group' => 'Technology',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['technologies'],
                    'contact' => ['company.technologies'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 50,
                'active' => true,
            ],
            [
                'id' => 'employee_count',
                'label' => 'Employee Count',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'range',
                'input' => 'range', // or select with ranges
                'data_source' => 'predefined', // Usually ranges are predefined or min/max
                'fields' => [
                    'company' => ['number_of_employees'],
                    'contact' => ['company.number_of_employees'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'range', 'supports_exclusion' => false],
                'aggregation' => [
                    'enabled' => true,
                    'type' => 'range',
                    'ranges' => [
                        ['key' => '1-10', 'from' => 1, 'to' => 10],
                        ['key' => '10-50', 'from' => 10, 'to' => 50],
                        ['key' => '50-200', 'from' => 50, 'to' => 200],
                        ['key' => '200-500', 'from' => 200, 'to' => 500],
                        ['key' => '500+', 'from' => 500],
                    ],
                ],
                'sort_order' => 60,
                'active' => true,
            ],
            [
                'id' => 'annual_revenue',
                'label' => 'Annual Revenue (USD)',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'range',
                'input' => 'range',
                'data_source' => 'predefined',
                'options' => [
                    ['label' => '$0 - $1M', 'value' => ['min' => 0, 'max' => 1000000]],
                    ['label' => '$1M - $10M', 'value' => ['min' => 1000000, 'max' => 10000000]],
                    ['label' => '$10M - $50M', 'value' => ['min' => 10000000, 'max' => 50000000]],
                    ['label' => '$50M - $100M', 'value' => ['min' => 50000000, 'max' => 100000000]],
                    ['label' => '$100M - $500M', 'value' => ['min' => 100000000, 'max' => 500000000]],
                    ['label' => '$500M+', 'value' => ['min' => 500000000, 'max' => null]],
                ],
                'fields' => [
                    'company' => ['annual_revenue_usd'],
                    'contact' => ['company.annual_revenue_usd'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'range', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 70,
                'active' => true,
            ],
            // [
            //     'id' => 'total_funding',
            //     'label' => 'Total Funding (USD)',
            //     'group' => 'Funding',
            //     'applies_to' => ['company', 'contact'],
            //     'type' => 'range',
            //     'input' => 'range',
            //     'data_source' => 'predefined',
            //     'fields' => [
            //         'company' => ['total_funding_usd'],
            //         'contact' => ['company.total_funding_usd'],
            //     ],
            //     'search' => ['enabled' => false],
            //     'filtering' => ['mode' => 'range', 'supports_exclusion' => false],
            //     'aggregation' => ['enabled' => false],
            //     'sort_order' => 80,
            //     'active' => true,
            // ],
            // [
            //     'id' => 'latest_funding_amount',
            //     'label' => 'Latest Funding Amount',
            //     'group' => 'Funding',
            //     'applies_to' => ['company', 'contact'],
            //     'type' => 'range',
            //     'input' => 'range',
            //     'data_source' => 'predefined',
            //     'fields' => [
            //         'company' => ['latest_funding_amount'],
            //         'contact' => ['company.latest_funding_amount'],
            //     ],
            //     'search' => ['enabled' => false],
            //     'filtering' => ['mode' => 'range', 'supports_exclusion' => false],
            //     'aggregation' => ['enabled' => false],
            //     'sort_order' => 85,
            //     'active' => true,
            // ],  
            // [
            //     'id' => 'latest_funding_round',
            //     'label' => 'Latest Funding Round',
            //     'group' => 'Funding',
            //     'applies_to' => ['company', 'contact'],
            //     'type' => 'keyword',
            //     'input' => 'multi_select',
            //     'data_source' => 'elasticsearch',
            //     'fields' => [
            //         'company' => ['latest_funding'],
            //         'contact' => ['company.latest_funding'],
            //     ],
            //     'search' => ['enabled' => true],
            //     'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
            //     'aggregation' => ['enabled' => true, 'size' => 100],
            //     'sort_order' => 90,
            //     'active' => true,
            // ],
            [
                'id' => 'founded_year',
                'label' => 'Founded Year',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'range',
                'input' => 'range',
                'data_source' => 'predefined',
                'fields' => [
                    'company' => ['founded_year'],
                    'contact' => ['company.founded_year'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'range', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 100,
                'active' => true,
            ],
            [
                'id' => 'last_raised_at',
                'label' => 'Last Raised Date',
                'group' => 'Funding',
                'applies_to' => ['company', 'contact'],
                'type' => 'date',
                'input' => 'range', // date range
                'data_source' => 'direct',
                'fields' => [
                    'company' => ['last_raised_at'],
                    'contact' => ['company.last_raised_at'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'range', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 110,
                'active' => true,
            ],
            // --- Boolean Filters (Company) ---
            [
                'id' => 'company_phone_exists',
                'label' => 'Company Phone Exists',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'company' => ['phone_number'],
                    'contact' => ['company.phone_number'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 120,
                'active' => true,
            ],
            [
                'id' => 'company_linkedin_exists',
                'label' => 'Company LinkedIn Exists',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'company' => ['linkedin_url'],
                    'contact' => ['company.linkedin_url'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 130,
                'active' => true,
            ],
            [
                'id' => 'company_facebook_exists',
                'label' => 'Company Facebook Exists',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'company' => ['facebook_url'],
                    'contact' => ['company.facebook_url'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 140,
                'active' => true,
            ],
            [
                'id' => 'company_twitter_exists',
                'label' => 'Company Twitter Exists',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'company' => ['twitter_url'],
                    'contact' => ['company.twitter_url'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 150,
                'active' => true,
            ],

            // --- Contact Filters ---
            [
                'id' => 'first_name',
                'label' => 'First Name',
                'group' => 'Personal',
                'applies_to' => ['contact'], // Only applies to contact context
                'type' => 'direct',
                'input' => 'text',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['first_name'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'term', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => false],
                'sort_order' => 200,
                'active' => true,
            ],
            [
                'id' => 'last_name',
                'label' => 'Last Name',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'direct',
                'input' => 'text',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['last_name'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'term', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => false],
                'sort_order' => 210,
                'active' => true,
            ],
            [
                'id' => 'job_title',
                'label' => 'Job Title',
                'group' => 'Role',
                'applies_to' => ['contact'],
                'type' => 'text',
                'input' => 'multi_select', // text + facet, allowing multi selection
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['title'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 220,
                'active' => true,
            ],
            [
                'id' => 'seniority',
                'label' => 'Seniority',
                'group' => 'Role',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['seniority'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 230,
                'active' => true,
            ],
            [
                'id' => 'department',
                'label' => 'Department',
                'group' => 'Role',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['departments'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 240,
                'active' => true,
            ],
            // --- Boolean Filters (Contact) ---
            [
                'id' => 'work_email_exists',
                'label' => 'Work Email Exists',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['work_email'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 250,
                'active' => true,
            ],
            [
                'id' => 'personal_email_exists',
                'label' => 'Personal Email Exists',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['personal_email'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 260,
                'active' => true,
            ],
            [
                'id' => 'mobile_number_exists',
                'label' => 'Mobile Number Exists',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['mobile_number'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 270,
                'active' => true,
            ],
            [
                'id' => 'direct_number_exists',
                'label' => 'Direct Number Exists',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['direct_number'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 280,
                'active' => true,
            ],
            [
                'id' => 'contact_linkedin_exists',
                'label' => 'LinkedIn Profile Exists',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['person_linkedin_url'],
                ],
                'search' => ['enabled' => false],
                'filtering' => ['mode' => 'exists', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => false],
                'sort_order' => 290,
                'active' => true,
            ],

            // --- Location Filters ---
            // Contact Location (Primary for contacts)
            [
                'id' => 'contact_country',
                'label' => 'Country',
                'group' => 'Location',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['location.country'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 300,
                'active' => true,
            ],
            [
                'id' => 'contact_state',
                'label' => 'State',
                'group' => 'Location',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['location.state'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 310,
                'active' => true,
            ],
            [
                'id' => 'contact_city',
                'label' => 'City',
                'group' => 'Location',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['location.city'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 320,
                'active' => true,
            ],

            // Company Location (Primary for companies, Secondary for contacts)
            [
                'id' => 'company_country',
                'label' => 'Company Country',
                'group' => 'Company Location', // Distinct group for clarity on contact page
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['location.country'],
                    'contact' => ['company.location.country'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 330,
                'active' => true,
            ],
            [
                'id' => 'company_state',
                'label' => 'Company State',
                'group' => 'Company Location',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['location.state'],
                    'contact' => ['company.location.state'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 340,
                'active' => true,
            ],
            [
                'id' => 'company_city',
                'label' => 'Company City',
                'group' => 'Company Location',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['location.city'],
                    'contact' => ['company.location.city'],
                ],
                'search' => ['enabled' => true],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 350,
                'active' => true,
            ],
        ];
    }
}
